fedora-selinux/selinux-policy

pdns.fc
pdns.if
pdns.te

Signed-off-by: Ruben Kerkhof <ruben@rubenkerkhof.com>

Initial pdns policy module

---

policy/modules/system/lvm.if

Add interface "lvm_manage_lock" to lvm policy.

---

policy/modules/system/lvm.if

-Allow caller to create /var/lock/lvm directory.

"lvm_manage_lock" interface upgrade.

---

apache.fc
jetty.fc
jetty.if
jetty.te

Finish policy for jetty (previous version provided only interfaces - no entrypoint). 

---

virt.if

Add interface allowing sending and receiving messages from virt over dbus

---

policy/modules/system/ipsec.te

Pull request #8, reworked.
Tested to work.

Update the policy for NetworkManager-libreswan-1.0.6

---

policy/modules/system/userdomain.if

Fix summary for userdom_user_tmp_content interface

---

bind.te

Allow named to bind on ephemeral ports - backport

---

iscsi.te

Allow iscsid create netlink iscsid sockets. - backport

---

hostapd.te

New AVC after kernel update. 
BZ#1266068

Allow hostapd to create netlink_generic_socket.

---

policy/modules/system/systemd.te

These are AVC's I am seeing in Rawhide.

New access needed by systemd domains

---

policy/modules/system/systemd.fc
policy/modules/system/systemd.if
policy/modules/system/systemd.te
policy/modules/system/userdomain.if

BZ#1266153
Corresponding F23 bugs (CLOSED):
BZ#1277987
BZ#1255238

Systemd-logind shutdown schedule issue - backport from F23

---

setroubleshoot.te

This is the https://github.com/fedora-selinux/selinux-policy/pull/92 request but for f23 and with e4f94f30882f906ea6d661dfe982deedf515ba3a patch from rawhide-contrib branch

F23 contrib setroubleshoot fixit

---

collectd.te

Allow collectd setgid capability

---

policy/modules/kernel/kernel.if

We want to dontaudit attempts by rkt containers to write to userhelper.

rawhide-Rktrawhide

---

policy/modules/kernel/filesystem.if
policy/modules/kernel/filesystem.te

Need this policy for fixing
https://bugzilla.redhat.com/show_bug.cgi?id=1330141

Add support for onloadfs

---

inetd.te
rsync.te

These fixes are for
https://bugzilla.redhat.com/show_bug.cgi?id=1343685

Idenitfy these domains as init daemons

---

policy/modules/system/unconfined.te

This will allow new container daemons to automatically work with
container process types.

Lots of new domains like OCID and RKT are user container processes

---

sssd.te

It will be required also in f24+

Allow sssd_t domain setpgid BZ(1411437)

---

sssd.fc
sssd.if

Also add named_filetrans interface to make sure all labels are correct.

Add sssd_secrets labeling
