fedora-selinux/selinux-policy

couchdb.te
selinux-policy-3.13.1-103.fc21
This commit fixes an issue where on Fedora 21 couchdb currently fails to start because it cannot `sendto` to systemd.
```
type=AVC msg=audit(1419910248.390:2287): avc:  denied  { sendto } for  pid=32469 comm="beam.smp" path="/run/systemd/notify" scontext=system_u:system_r:couchdb_t:s0 tcontext=system_u:system_r:kernel_t:s0 tclass=unix_dgram_socket permissive=0
type=SYSCALL msg=audit(1419910248.390:2287): arch=c000003e syscall=46 success=no exit=-13 a0=10 a1=7fa64d3bbc50 a2=4000 a3=1 items=0 ppid=1 pid=32469 auid=4294967295 uid=986 gid=983 euid=986 suid=986 fsuid=986 egid=983 sgid=983 fsgid=983 tty=(none) ses=4294967295 comm="beam.smp" exe="/usr/lib64/erlang/erts-6.3/bin/beam.smp" subj=system_u:system_r:couchdb_t:s0 key=(null)
```
=> couchdb: Allow couchdb to sendto kernel unix domain sockets

openvswitch.te
openvswitch needs to search network sysctl entries as well as read them.
Related to: https://bugzilla.redhat.com/show_bug.cgi?id=1177632
=> openvswitch needs to search network sysctl

glusterd.te, passenger.te, rkhunter.te, stapserver.te
These are cosmetic changes needed for fluent transition to
libsemanage-2.4. Since the CIL is used, a module name is not stored in
module but a filename is used instead. With these changes, modules names before update to libsemanage-2.4 will be same as after update.
=> rename several contrib modules according to their filenames

targetd.te
- Allow raw fixed disk device read (required for normal daemon operation on server machines).
=> Targetd policy upgrade.

networkmanager.te
Recently NetworkManager gained support for writing messages to the
audit subsystem; add a rule to allow that.
Reproducer:
- set "audit=yes" in [logging] section of /etc/NetworkManager/NetworkManager.conf
- restart NetworkManager
- perform an action that triggers an audit message, for example "nmcli connection add con-name test type ethernet ifname eth0"
AVC denial messages:
type=AVC msg=audit(1440071103.359:1390): avc:  denied  { create } for  pid=22136 comm="NetworkManager" scontext=system_u:system_r:NetworkManager_t:s0 tcontext=system_u:system_r:NetworkManager_t:s0 tclass=netlink_audit_socket permissive=1
type=AVC msg=audit(1440071103.361:1391): avc:  denied  { nlmsg_relay } for  pid=22136 comm="NetworkManager" scontext=system_u:system_r:NetworkManager_t:s0 …
=> Allow NetworkManager to write audit log messages

policy/modules/kernel/filesystem.if
Efivarfs contains Linux Kernel configuration options for UEFI systems (UEFI Runtime Variables)
=> Add interface to allow reading files in efivarfs

policy/modules/system/systemd.te
BZ #1244973, #1267207 (partial solution)
=> Allow systemd-logind read access to efivarfs

networkmanager.te, policykit.te
=> Allow NetworkManager_t and policykit_t read access to systemd-machined pid files. 

policy/modules/kernel/filesystem.if, policy/modules/system/systemd.te
BZ #1244973
Already merged to rawhide.
=> Add interface to allow reading files in efivarfs - contains Linux Kernel configuration options for UEFI systems (UEFI Runtime Variables)

policy/modules/kernel/corenetwork.if.in
I am Fedora Zh User Group member. I call the "corenet_tcp_bind_unreserved_ports (ircd_hybrid_t)" in the module, but returned the following error when installing the module.
```
$ sudo semodule -i ircd-hybrid.pp
libsepol.type_copy_callback: ircd-hybrid: Expected unreserved_port_t to be an attribute, but it was already declared as a type. (No such file or directory).
libsemanage.semanage_link_sandbox: Link packages failed (No such file or directory).
semodule:  Failed!
```
I find "unreserved_port_type" attributes name is incorrectly written as "unreserved_port_t".
```
grep -n "attribute unreserved_port_t" policy/modules/kernel/corenetwork.if.in
2268:		attribute unreserved_port_type;
2286:		attribute unreserved_port_type;
2304:		attribute unreserved_port_t;          < ----------
2322: …
```
=> Fix attribute in corenetwork.if.in BZ(#1272426)

policy/modules/system/ipsec.te
StrongSwan has an IPSec IKE daemon and the NetworkManager plugin in the same
binary. They don't split it into a mgmt daemon and actual IPSec daemon.
Also, it uses tun/tap:
<pre>
avc:  denied  { read write } for
pid=9755 comm="charon-nm" name="tun" dev="devtmpfs" ino=7165
scontext=system_u:system_r:ipsec_t:s0
tcontext=system_u:object_r:tun_tap_device_t:s0
tclass=chr_file
avc:  denied  { open } for
pid=9755 comm="charon-nm" path="/dev/net/tun" dev="devtmpfs" ino=7165
scontext=system_u:system_r:ipsec_t:s0
tcontext=system_u:object_r:tun_tap_device_t:s0
tclass=chr_file
avc:  denied  { ioctl } for
pid=9755 comm="charon-nm" path="/dev/net/tun" dev="devtmpfs" ino=7165
scontext=system_u:system_r:ipsec_t:s0
tcontext=system_u:object_r:tun_tap_device_t:s0
tclass=chr_file
avc:  denied  { create } for …
=> ipsec: fix strongSwan charon-nm

lircd.te
New try: Add some new permission needed for new code dropping root privileges using setuid()
=> lircd: Fix new drop-root-permissions denials (v2)

policy/modules/system/sysnetwork.te
=> Allow systemd-hostnamed to communicate with dhcp via dbus. 

antivirus.te
Clamd binds to random unassigned port (by default in range 1024-2048). 
BZ #1248785
=> Allow antivirus_t to bind to all unreserved ports.

apm.te
=> Allow acpid to attempt to connect to the Linux kernel via generic netlink socket.

thumb.te
There is no reason for totem-video-thu to use console.
BZ #1282170
=> Dontaudit attempts of thumb_t to use console output. 

antivirus.te
It randomly chooses port in range 1024-2048 (by default), some of which are assigned.
BZ #1248785
=> Dontaudit attempts of antivirus_t to bind to reserved ports. 

mozilla.te
The folder is created and used by linphone web plugin. 
BZ#1279752
=> Add transition for ".linphone-web" to mozilla_plugin_t.

nut.te
Allow uspsmon to use kill within its domain. BZ #1276861
=> Allow uspsmon reading form rand/urand. BZ #1282103, #1282104, #1282105

puppet.if
Looks like in refpolicy this is correct.
=> Allow reading of symlinks in the read_config

mysql.fc
to /var/lib/mysql-files by default[1].
This affects the LOAD DATA and SELECT ... INTO OUTFILE statements
and the LOAD_FILE() function. For these to work mysqld needs write
and read access to files in /var/lib/mysql-files.
Modify policy to allow this.
MySQL supports special debug variant[2], this is shipped in some
packages of MySQL server.
Add mysqld-debug as mysqld server executable variant in policy.
[1]: http://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_secure_file_priv
[2]: http://dev.mysql.com/doc/refman/5.7/en/debugging-server.html
=> Starting with MySQL 5.7, mysqld option --secure-file-priv is set

setroubleshoot.te
sealert, which is run via org.fedoraproject.SetroubleshootFixit DBUS
service, is labaled as setroubleshoot_fixit_t and as it indirectly uses
libffi for signal handlers, it needs to be able to create and mmap
temporary files
Fixes: rhbz#1278983
=> Allow setroubleshoot_fixit_t to use temporary files

lttng-tools.fc, lttng-tools.if, lttng-tools.te
A new policy for lttng-sessiond daemon. It creates /dev/shm/lttng-ust-wait-5 which is accessed by random services using lttng for kernel tracing.
This is an initial policy to have labeling for dev/shm/lttng-ust-wait-5  and to identify consumers (like Ceph for example).
=> Add SELinux policy for LTTng 2.x central tracing registry daemon.

mysql.fc
As of MySQL 5.7.11, InnoDB supports data encryption for InnoDB tables
stored in file-per-table tablespaces[1].
To manage the master key, a keyring_file plugin is used. This plugin
needs read and write to directory /var/lib/mysql-keyring, add
directory to policy.
[1]: https://dev.mysql.com/doc/refman/5.7/en/innodb-tablespace-encryption.html
=> Support for InnoDB Tablespace Encryption.

virt.if
We need the following policy
optional_policy(`
require {
type svirt_lxc_net_t;
type unconfined_t;
}
virt_stub_svirt_sandbox_file()
allow unconfined_t svirt_sandbox_file_t:file entrypoint;
allow docker_t svirt_sandbox_file_t:file entrypoint;
typebounds unconfined_t docker_t;
typebounds docker_t svirt_lxc_net_t;
')
=> Fixed to make SELinux work with docker and prctl(NO_NEW_PRIVS)

virt.fc, virt.te
We need to add container_image_t for read/execute content for containers.  I think we should break this code and all of the svirt_lxc_net_t code into a separate container.te module that we can ship independantly like we do with docker-selinux.te.  I would also like to get rid of docker-selinux.te and make it container.te.  But that might be difficult.
=> rkt needs these rules to run locked down containers

virt.fc, virt.if, virt.te
The virtlogd daemon is currently given the same context as
libvirtd. This is essentially unrestricted host access which
is not at all desirable. The virtlogd daemon is a small single
purpose daemon whose only job is logging. It should have a
dedicated context which strictly controls what it is permitted
todo.
Signed-off-by: Daniel P. Berrange <berrange@redhat.com>
=> virt: add strict policy for virtlogd daemon

policy/modules/services/xserver.fc
Changing this will cause all /dev/nvidia* devices get created with the i
correct label.
=> Label all nvidia binaries as xserver_exec_t

modemmanager.te
ModemManager uses logind's sleep inhibitor capability.
avc:  denied { send_msg } for msgtype=method_call
in exe="/usr/bin/dbus-daemon" sauid=81
hostname=? addr=? terminal=?
=> Allow modemmanager to talk to logind

policy/modules/system/init.te
When running rkt it will transition to svirt_lxc_net_t
for confined containers, these transitions will allow
you to run rkt as a system service.
=> Allow rkt to run out of systemd unit files

policy/modules/kernel/files.if
Since it is a file_type we need to remove from this line.
=> unlabeled_t can not be an entrypoint.

dnsmasq.if, dnsmasq.te, networkmanager.te
Since bug https://bugzilla.gnome.org/show_bug.cgi?id=765043,
NetworkManager will control dnsmasq via its D-Bus interface
instead of re-starting the process with static configuration.
type=USER_AVC msg=audit(1461325861.280:1477): pid=1099 uid=81 auid=4294967295 ses=4294967295 subj=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 msg='avc:  denied  { send_msg } for msgtype=signal interface=org.freedesktop.NetworkManager.dnsmasq member=Up dest=org.freedesktop.DBus spid=11580 tpid=11540 scontext=system_u:system_r:dnsmasq_t:s0 tcontext=system_u:system_r:NetworkManager_t:s0 tclass=dbus  exe="/usr/bin/dbus-daemon" sauid=81 hostname=? addr=? terminal=?'
type=USER_AVC msg=audit(1461325861.463:1478): pid=1099 uid=81 auid=4294967295 ses=4294967295 subj=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 …
=> dnsmasq: allow NetworkManager to control dnsmasq via D-Bus

policy/modules/kernel/devices.te, policy/modules/kernel/kernel.te
Allow unconfined domains to getattr on all device-node objects
Allow unconfined domains full access to systclt_type lnk_files.
type-bounds checks are giving errors on this since docker_t is allowed
this access.
=> Additional access required for unconfined domains

tmpreaper.te
problem
----------
tmpwatch fails to delete files in directories without read and setattr rights wenn started from cron.
findings
----------
* It already allows setattr on some but not on all.
* tmpreaper_t already has the ability to delete all non_security_file_type files.
*  Having the ability to delete files of this type but not reading directories of the same type seems wrong.
solution
----------
allow `tmpreaper_t` permissions `read` and `setattr` on all `non_security_file_type directories`.
reproduced on
-------------------
RHEL7, Fedora 23
fix (basic) tested on
-------------------------
RHEL7, Fedora 23
reproduction steps
------------------------
```
mkdir /var/log/test; touch --date "2015-01-01" /var/log/test/test.log; ls -lZ /var/log/test/test.log
echo '* * * * * root …
```
=> Allow tmpreaper_t to read/setattr all non_security_file_type dirs

policy/modules/kernel/domain.te, policy/modules/system/unconfined.if, policy/modules/system/userdomain.te
Need to allow user domains to have create so that tools like crome will
work correctly.  Probably future use cases as well.
=> User Namespace is requires create on process domains

puppet.te
If puppet executes /sbin/shorewall it won't transition to
shorewall_t and create log files with puppet_log_t context
instead of shorewall_log_t. If service is then managed by
init (sysv/systemd) it will fail to start.
If puppet_t is allowed to transtition to shorewall_t the
logfile will get the correct shorewall_log_t type.
Adapted from TresysTechnology/refpolicy-contrib commit
ea5a6aa58e0d545e812c234ee28dc4d259fa2e77 and
11576979ca3306042abe008aa4b5df6a95c111dd
=> Allow puppet_t transtition to shorewall_t

virt.te
"Customer is reporting that any SCTP connections inside a container are failing,
due to an error in recvmsg(). "
https://bugzilla.redhat.com/show_bug.cgi?id=1349956
=> Container processes need to be able to listen on rawip sockets

policy/modules/roles/sysadm.te
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1253582
=> sysadmin should be allowed to use docker.

policy/modules/kernel/domain.te, policy/modules/system/init.te, policy/modules/system/systemd.te
Unconfined domains should have the same access to userns capabilties as
they do to real capabilities.
Userdomains that can execute chrome need sys_admin sys_chroot
sys_ptrace capabilities, they probbaly will need more,
but I don't know for sure.
=> Add support for user namespace

policy/modules/system/init.te
Looks like devices created during boot are in /run/systemd/inaccessible/blk
/run/systemd/inaccessible/chr
ls -l /run/systemd/inaccessible/
total 0
b---------. 1 root root 0, 0 Aug  7 06:07 blk
c---------. 1 root root 0, 0 Aug  7 06:07 chr
d---------. 2 root root   40 Aug  7 06:07 dir
p---------. 1 root root    0 Aug  7 06:07 fifo
----------. 1 root root    0 Aug  7 06:07 reg
s---------. 1 root root    0 Aug  7 06:07 sock
Maybe could dontaudit these, but getattr access is probably ok.
=> systemd is doing a gettattr on blk and chr devices in /run

virt.fc, virt.if, virt.te
Also add container_ro_file_t, for a type that can be shared into a container
as r/o/x permissions, but no write.
=> Change container_image_t to container_file_t

policy/modules/kernel/filesystem.if, policy/modules/system/userdomain.if
Otherwise chrome crashes when run from staff_t.
=> These allow rules are requiered to allow chrome to setup user namespace

policy/modules/system/init.te, policy/modules/system/systemd.if, policy/modules/system/systemd.te
Based on feedback from https://github.com/fedora-selinux/selinux-policy/pull/156
by Dominic Grift.
=> Add systemd_mount_dir to deal with service using ReadOnlyDirectory

cups.if, cups.te
Seems that you need to read cups socket now to get list of printers.
=> Allow domains that can use the cups socket to read it also.

dbus.te, virt.if
When running a systemd container, we want to list the contents of the journal.
This is done using a command like
journalctl -M CONTAINERUUID
Which causes and avc when system dbus examines the content of the /var/log/journal inside of the container.
=> Allow system_dbusd to list sandbox dirs

sandbox.te, sandboxX.te, virt.te
If we do this using docker or bubblewrap using the NO_NEW_PRIVS
the transition will fail, this change allows the containers to transition.
=> Allow users to transition from unconfined_t to container types

virt.te
Customers have requested management of NFS Shares from
a confined domain.
Also we should not allow a confined domain to load kernel modules.
=> Add boolean to allow sandbox domains to mount nfs

firewalld.te
This is needed for secure use of netfilter connection tracking helpers.
There is no interface in netfilter to get the list of supported netfilter
connection tracking modules and the helpers they provide. To be able to know
which are usable with the active kernel, firewalld needs to be able to list
the directory "/lib/modules/$(uname -r)/kernel/net/netfilter/" and use
modinfo on the modules that start with "nf_conntrack_" to get the helpers.
=> Allow firewalld to getattr open search read modules_object_t:dir

puppet.te
Running a puppet exec resource with timedatectl as
command, auditd logs this error:
```
type=USER_AVC
msg=audit(11/21/2016 15:04:49.306:59375) :
pid=741
uid=dbus auid=unset ses=unset
subj=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023
msg='avc:  denied  { send_msg } for msgtype=method_return dest=:1.1421 spid=31613 tpid=31615
scontext=system_u:system_r:systemd_timedated_t:s0
tcontext=system_u:system_r:puppetagent_t:s0
tclass=dbus
exe=/usr/bin/dbus-daemon sauid=dbus
hostname=? addr=? terminal=?'
```
Use the systemd_dbus_chat_timedated interface to allow
puppetagent_t the access.
=> Allow puppetagent_t to access timedated dbus

policy/modules/kernel/domain.if, policy/modules/roles/unconfineduser.if
Need these rules to allow unconfined domains to transiton to sandbox
domains over all entrypoints
=> unconfined_exec_t typebound all exec_type

policy/modules/kernel/kernel.if, policy/modules/system/init.te
Added to systemd in https://github.com/systemd/systemd/commit/00d9ef8560.
=> Allow systemd to send user information back to pid1. BZ(1412750)

policy/modules/system/init.te
Fixup for 8279b91986. I thought that kernel_rw_stream_socket_perms
is a superset of kernel_stream_connect, but apparently not:
type=AVC msg=audit(1486044204.161:366): avc:  denied  { connectto } for  pid=2846 comm="(spatcher)" path="/run/systemd/journal/stdout" scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:kernel_t:s0 tclass=unix_stream_socket permissive=0
https://bugzilla.redhat.com/show_bug.cgi?id=1418682
=> Restore connecto permssions for init_t
